# Generated by Django 4.2.3 on 2024-10-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coderschroniclesapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='image',
            field=models.ImageField(default='', upload_to='attachments/'),
        ),
    ]
